spring:
  application:
    name: spring-data-redis
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: -1
        min-idle: 3
server:
  port: 33000
  servlet:
    context-path: /redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:32000/eureka


