spring:
  application:
    name: ZuulServer

server:
  port: 32010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32000/eureka

#zuul:
#  routes:
#    routes-zuul: /control/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
zuul:
  ribbon-isolation-strategy: thread
  routes:
    zuul-client-a:
      path: /client/**
      service-id: zuul-client-a
      senstiveHeaders: Cookie, Set-Cookie, Authorization
  ignored-services: "*"
ribbon:
  eureka:
    enabled: true