spring:
  application:
    name: eureka-client-1
  boot:
    admin:
      client:
        url: http://localhost:31000
server:
  port: 32001
  servlet:
    context-path: /eureka-client-1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32000/eureka

# 暴露 Hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'