spring:
  application:
    name: cloud-hystrix

server:
  port: 32006
  servlet:
    context-path: /hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32000/eureka
feign:
  hystrix:
    enabled: true
