spring:
  application:
    name: cloud-hystrix
  boot:
    admin:
      client:
        url: http://localhost:31000
server:
  port: 32006
  servlet:
    context-path: /hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32000/eureka
feign:
  hystrix:
    enabled: true
