spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: gateway-client-a
        uri: lb://gateway-client-a
        predicates:
          - Path=/client/**
        filters:
          - StripPrefix=1
server:
  port: 32020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:32000/eureka
