spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      # 跨域
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gateway-client-a
          uri: lb://gateway-client-a
          #          uri: http://localhost:32021
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
server:
  port: 32020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:32000/eureka
