spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:31000
server:
  port: 32000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:32000/eureka

  # 心跳检测机制
  instance:
    lease-renewal-interval-in-seconds: 20
#  server:
#    enable-self-preservation: false