spring:
  application:
    name: feign-client
  boot:
    admin:
      client:
        url: http://localhost:31000
server:
  port: 32004
  servlet:
    context-path: /client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32000/eureka
