spring:
  application:
    name: spring-aop
  boot:
    admin:
      client:
        url: http://localhost:31000

server:
  port: 32012
  servlet:
    context-path: /aop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:32000/eureka