spring:
  application:
    name: feign-server
  boot:
    admin:
      client:
        url: http://localhost:31000
server:
  port: 32003
  servlet:
    context-path: /feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32000/eureka
